language: python
sudo: false
python:
  - "3.4"

install:
  - "pip install -e ."
  - "pip install coveralls"
  - "pip install pyflakes"
  - "pip install pep8"

script:
  - "coverage run --source=verktyg_sqlalchemy setup.py test"
  - "pep8 verktyg_sqlalchemy setup.py"
  - "pyflakes verktyg_sqlalchemy setup.py"

after_success:
  - "coveralls"
